package com.revature.model;

public class Reimbursement {

	private int reimbursementid; 
	private int requestid;
	private double reimbursementamount;
	private String reimbursementdate;
	
	// generated by Source Menu - Constructor
	public Reimbursement(int reimbursementid, int requestid, double reimbursementamount, String reimbursementdate) {
		super();
		this.reimbursementid = reimbursementid;
		this.requestid = requestid;
		this.reimbursementamount = reimbursementamount;
		this.reimbursementdate = reimbursementdate;
	}
	
	// generated by Source Menu - Getters and Setters
	public int getReimbursementid() {
		return reimbursementid;
	}

	public void setReimbursementid(int reimbursementid) {
		this.reimbursementid = reimbursementid;
	}

	public int getRequestid() {
		return requestid;
	}

	public void setRequestid(int requestid) {
		this.requestid = requestid;
	}

	public double getReimbursementamount() {
		return reimbursementamount;
	}

	public void setReimbursementamount(double reimbursementamount) {
		this.reimbursementamount = reimbursementamount;
	}

	public String getReimbursementdate() {
		return reimbursementdate;
	}

	public void setReimbursementdate(String reimbursementdate) {
		this.reimbursementdate = reimbursementdate;
	}

	// generated by SourceMenu - toString
	@Override
	public String toString() {
		return "Reimbursement [reimbursementid=" + reimbursementid + ", requestid=" + requestid
				+ ", reimbursementamount=" + reimbursementamount + ", reimbursementdate=" + reimbursementdate + "]";
	}
	
	
	
}
