package com.revature.model;

public class Request {
	
	private int requestid;
	private int employeeid;
	private int requestvalue;
	private String requeststatus;
	private String requestdate;
	private String eventdate;
	
	//generate by Source Menu - Constructor
	public Request(int requestid, int employeeid, int requestvalue, String requeststatus, String requestdate,
			String eventdate) {
		super();
		this.requestid = requestid;
		this.employeeid = employeeid;
		this.requestvalue = requestvalue;
		this.requeststatus = requeststatus;
		this.requestdate = requestdate;
		this.eventdate = eventdate;
	}
	
	//generate by Source Menu - Getter and Setter
	public int getRequestid() {
		return requestid;
	}
	public void setRequestid(int requestid) {
		this.requestid = requestid;
	}
	public int getEmployeeid() {
		return employeeid;
	}
	public void setEmployeeid(int employeeid) {
		this.employeeid = employeeid;
	}
	public int getRequestvalue() {
		return requestvalue;
	}
	public void setRequestvalue(int requestvalue) {
		this.requestvalue = requestvalue;
	}
	public String getRequeststatus() {
		return requeststatus;
	}
	public void setRequeststatus(String requeststatus) {
		this.requeststatus = requeststatus;
	}
	public String getRequestdate() {
		return requestdate;
	}
	public void setRequestdate(String requestdate) {
		this.requestdate = requestdate;
	}
	public String getEventdate() {
		return eventdate;
	}
	public void setEventdate(String eventdate) {
		this.eventdate = eventdate;
	}
	
	//generated by Source Menu - toString
	@Override
	public String toString() {
		return "Request [requestid=" + requestid + ", employeeid=" + employeeid + ", requestvalue=" + requestvalue
				+ ", requeststatus=" + requeststatus + ", requestdate=" + requestdate + ", eventdate=" + eventdate
				+ "]";
	}
	
	
}
