package com.revature.model;

import java.sql.Date;

public class Reimbursement {

	private int reimbursementid; 
	
	private double reimbursementamount;
	private Date reimbursementdate;
	
	// generated by Source Menu - Constructor
	public Reimbursement(int reimbursementid, double reimbursementamount, Date reimbursementdate) {
		super();
		this.reimbursementid = reimbursementid;
		this.reimbursementamount = reimbursementamount;
		this.reimbursementdate = reimbursementdate;
	}
	
	// generated by Source Menu - Getters and Setters
	public int getReimbursementid() {
		return reimbursementid;
	}

	public void setReimbursementid(int reimbursementid) {
		this.reimbursementid = reimbursementid;
	}

	public double getReimbursementamount() {
		return reimbursementamount;
	}

	public void setReimbursementamount(double reimbursementamount) {
		this.reimbursementamount = reimbursementamount;
	}

	public Date getReimbursementdate() {
		return reimbursementdate;
	}

	public void setReimbursementdate(Date reimbursementdate) {
		this.reimbursementdate = reimbursementdate;
	}

	// generated by SourceMenu - toString
	@Override
	public String toString() {
		return "Reimbursement [reimbursementid=" + reimbursementid + ", reimbursementamount=" + reimbursementamount + ", reimbursementdate=" + reimbursementdate + "]";
	}
	
	
	
}
