package com.revature.model;

public class Employee {

	private int employeeid;
	private String employeelastname;
	private String employeefirstname;
	private String employeeposition;
	private String employeeemail;
	private String employeepassword;
	private int reportsto;
	
	//default constructor for jackson
	public Employee() {
		super();
	}

	// generated by Source Menu - Constructor
	public Employee(int employeeid, String employeelastname, String employeefirstname, String employeeposition,
			String employeeemail, String employeepassword) {
		super();
		this.employeeid = employeeid;
		this.employeelastname = employeelastname;
		this.employeefirstname = employeefirstname;
		this.employeeposition = employeeposition;
		this.employeeemail = employeeemail;
		this.employeepassword = employeepassword;
	}
	
	public Employee(int employeeid, String employeelastname, String employeefirstname, String employeeposition,
			String employeeemail, String employeepassword, int reportsto) {
		super();
		this.employeeid = employeeid;
		this.employeelastname = employeelastname;
		this.employeefirstname = employeefirstname;
		this.employeeposition = employeeposition;
		this.employeeemail = employeeemail;
		this.employeepassword = employeepassword;
		this.reportsto = reportsto;
	}	
	// generated by Source Menu - Getters and Setters
	public int getEmployeeid() {
		return employeeid;
	}

	public void setEmployeeid(int employeeid) {
		this.employeeid = employeeid;
	}

	public String getEmployeelastname() {
		return employeelastname;
	}

	public void setEmployeelastname(String employeelastname) {
		this.employeelastname = employeelastname;
	}

	public String getEmployeefirstname() {
		return employeefirstname;
	}

	public void setEmployeefirstname(String employeefirstname) {
		this.employeefirstname = employeefirstname;
	}

	public String getEmployeeposition() {
		return employeeposition;
	}

	public void setEmployeeposition(String employeeposition) {
		this.employeeposition = employeeposition;
	}

	public String getEmployeeemail() {
		return employeeemail;
	}

	public void setEmployeeemail(String employeeemail) {
		this.employeeemail = employeeemail;
	}

	public String getEmployeepassword() {
		return employeepassword;
	}

	public void setEmployeepassword(String employeepassword) {
		this.employeepassword = employeepassword;
	}

	public int getReportsto() {
		return reportsto;
	}

	public void setReportsto(int reportsto) {
		this.reportsto = reportsto;
	}
	// generated by Source Menu - toString
	@Override
//	public String toString() {
//		return "Employee [employeeid=" + employeeid + ", employeelastname=" + employeelastname + ", employeefirstname="
//				+ employeefirstname + ", employeeposition=" + employeeposition + ", employeeemail=" + employeeemail
//				+ ", employeepassword=" + employeepassword + "]";
//	}
	public String toString() {
		return "Employee Name:" + employeefirstname + " " +employeelastname + '\n' + "Employee ID: " + employeeid;
	}

	
	
	
	
}
