package com.revature.model;

public class Reports {

	private int reportid;
	private int managerid;
	private int employeeid;
	
	//generated by Source Menu - Constructor
	public Reports(int reportid, int managerid, int employeeid) {
		super();
		this.reportid = reportid;
		this.managerid = managerid;
		this.employeeid = employeeid;
	}
	
	//generated by Source Menu - Getters and Setters
	public int getReportid() {
		return reportid;
	}
	public void setReportid(int reportid) {
		this.reportid = reportid;
	}
	public int getManagerid() {
		return managerid;
	}
	public void setManagerid(int managerid) {
		this.managerid = managerid;
	}
	public int getEmployeeid() {
		return employeeid;
	}
	public void setEmployeeid(int employeeid) {
		this.employeeid = employeeid;
	}
	
	//generated by Source Menu - toString
	@Override
	public String toString() {
		return "Reports [reportid=" + reportid + ", managerid=" + managerid + ", employeeid=" + employeeid + "]";
	}
	
}
