package com.revature.model;

import java.sql.Date;

public class Request {
	
	private int requestid;
	private int requestvalue;
	private String requeststatus;
	private Date requestdate;
	private Date eventdate;
	
	//generate by Source Menu - Constructor
	public Request(int requestid, int requestvalue, String requeststatus, Date requestdate,
			Date eventdate) {
		super();
		this.requestid = requestid;
		this.requestvalue = requestvalue;
		this.requeststatus = requeststatus;
		this.requestdate = requestdate;
		this.eventdate = eventdate;
	}
	
	//generate by Source Menu - Getter and Setter
	public int getRequestid() {
		return requestid;
	}
	public void setRequestid(int requestid) {
		this.requestid = requestid;
	}
	public int getRequestvalue() {
		return requestvalue;
	}
	public void setRequestvalue(int requestvalue) {
		this.requestvalue = requestvalue;
	}
	public String getRequeststatus() {
		return requeststatus;
	}
	public void setRequeststatus(String requeststatus) {
		this.requeststatus = requeststatus;
	}
	public Date getRequestdate() {
		return requestdate;
	}
	public void setRequestdate(Date requestdate) {
		this.requestdate = requestdate;
	}
	public Date getEventdate() {
		return eventdate;
	}
	public void setEventdate(Date eventdate) {
		this.eventdate = eventdate;
	}
	
	//generated by Source Menu - toString
	@Override
	public String toString() {
		return "Request [requestid=" + requestid + ", requestvalue=" + requestvalue
				+ ", requeststatus=" + requeststatus + ", requestdate=" + requestdate + ", eventdate=" + eventdate
				+ "]";
	}
	
	
}
